// Generated by OrchidJS. Do not edit — this file is rewritten on every
// dev-server start, file change and build.

import type { OrchidService, OrchidDi, Logger } from "orchidjs"
import type __orchid_auth from "../src/services/auth"
import type __orchid_users from "../src/services/users"
import type __orchid_config from "../src/di/config"
import type __orchid_currentUser from "../src/di/currentUser"
import type __orchid_db from "../src/di/db"
import type __orchid_requestId from "../src/di/requestId"
import type __orchid_visits from "../src/di/visits"

declare module "orchidjs" {
  interface Ctx {
    /** The built-in logger. Override it with services/logger.ts. */
    logger: Logger
    auth: OrchidService<typeof __orchid_auth>
    users: OrchidService<typeof __orchid_users>
    config: OrchidDi<typeof __orchid_config>
    currentUser: OrchidDi<typeof __orchid_currentUser>
    db: OrchidDi<typeof __orchid_db>
    requestId: OrchidDi<typeof __orchid_requestId>
    visits: OrchidDi<typeof __orchid_visits>
  }
}

export {}
