import { mkdir, writeFile, readFile } from "node:fs/promises"
import { join, relative, dirname } from "node:path"
import { deriveContextKey } from "../scanner/paths.js"
import { walkDir } from "../scanner/walk.js"

export const OUTPUT_DIR = ".clove"
export const OUTPUT_FILE = "types.d.ts"

export interface CodegenOptions {
  /** Project root — the generated directory is created here. */
  rootDir: string
  /** Directory containing `services/` and `di/`. */
  sourceDir: string
  servicesDir?: string
  diDir?: string
}

interface Entry {
  key: string
  /** Import specifier relative to the generated file. */
  specifier: string
  kind: "service" | "di"
}

/**
 * Emits `.clove/types.d.ts`, which augments the `Ctx` interface with one
 * property per file in `services/` and `di/`.
 *
 * This is a pure path-level scan: files are never evaluated, so codegen stays
 * fast and cannot be broken by a module that throws at import time.
 */
export async function generateTypes(options: CodegenOptions): Promise<string> {
  const { rootDir, sourceDir } = options
  const servicesDir = join(sourceDir, options.servicesDir ?? "services")
  const diDir = join(sourceDir, options.diDir ?? "di")
  const outDir = join(rootDir, OUTPUT_DIR)
  const outFile = join(outDir, OUTPUT_FILE)

  const entries: Entry[] = []
  const seen = new Map<string, string>()

  for (const [dir, kind] of [
    [servicesDir, "service"],
    [diDir, "di"],
  ] as const) {
    for (const file of await walkDir(dir)) {
      const key = deriveContextKey(file.relative)
      const previous = seen.get(key)
      if (previous) {
        // Two files claiming one key is a boot error; the generated types just
        // keep the first so the file stays valid TypeScript for the editor.
        continue
      }
      seen.set(key, file.absolute)
      entries.push({
        key,
        specifier: importSpecifier(outDir, file.absolute),
        kind,
      })
    }
  }

  const contents = render(entries)

  await mkdir(outDir, { recursive: true })
  const existing = await readFile(outFile, "utf8").catch(() => null)
  if (existing !== contents) {
    await writeFile(outFile, contents, "utf8")
  }
  return outFile
}

function render(entries: Entry[]): string {
  const lines: string[] = [
    "// Generated by CloveJS. Do not edit — this file is rewritten on every",
    "// dev-server start, file change and build.",
    "",
  ]

  if (entries.length === 0) {
    lines.push(
      'declare module "clovejs" {',
      "  // No services or di values found yet.",
      "  // eslint-disable-next-line @typescript-eslint/no-empty-object-type",
      "  interface Ctx {}",
      "}",
      "",
      "export {}",
      "",
    )
    return lines.join("\n")
  }

  lines.push('import type { CloveService, CloveDi, Logger } from "clovejs"')
  for (const entry of entries) {
    lines.push(`import type ${identifier(entry.key)} from "${entry.specifier}"`)
  }
  lines.push("", 'declare module "clovejs" {', "  interface Ctx {")

  if (!entries.some((e) => e.key === "logger")) {
    lines.push("    /** The built-in logger. Override it with services/logger.ts. */")
    lines.push("    logger: Logger")
  }

  for (const entry of entries) {
    const wrapper = entry.kind === "service" ? "CloveService" : "CloveDi"
    lines.push(`    ${propertyName(entry.key)}: ${wrapper}<typeof ${identifier(entry.key)}>`)
  }

  lines.push("  }", "}", "", "export {}", "")
  return lines.join("\n")
}

/** A TypeScript-safe local alias for an imported definition. */
function identifier(key: string): string {
  return `__clove_${key.replace(/[^A-Za-z0-9_$]/g, "_")}`
}

function propertyName(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key)
}

function importSpecifier(fromDir: string, target: string): string {
  let rel = relative(fromDir, target).split("\\").join("/")
  if (!rel.startsWith(".")) rel = "./" + rel
  // TypeScript resolves the declaration from the source file, so the extension
  // is dropped rather than rewritten to .js.
  return rel.replace(/\.(m|c)?tsx?$/, "").replace(/\.(m|c)?jsx?$/, "")
}

/** Ensures the project's .gitignore covers the generated directory. */
export async function ensureGitignore(rootDir: string): Promise<void> {
  const path = join(rootDir, ".gitignore")
  const existing = await readFile(path, "utf8").catch(() => null)
  if (existing === null) return
  if (existing.split("\n").some((line) => line.trim() === `${OUTPUT_DIR}/`)) return
  await mkdir(dirname(path), { recursive: true })
  await writeFile(
    path,
    existing.replace(/\n*$/, "\n") + `\n# CloveJS generated types\n${OUTPUT_DIR}/\n`,
    "utf8",
  )
}
